# Цветовая схема Nord
foreground #D8DEE9
background #2E3440
selection_foreground #2E3440
selection_background #88C0D0

# Ледяной голубой (Цвета курсора и рамок)
cursor #81A1C1
active_border_color #88C0D0

# Прозрачность (как матовое стекло)
background_opacity 0.85
dynamic_background_opacity yes

# Шрифт
font_family JetBrains Mono
font_size 11.0
shell zsh
